### ISSUE TITLE
Quelle: Bild Anlageklassen

### ISSUE THREAD

**Issue by sectore** [BitcoinBeachTravemuende/DerBitcoinVirus#11]
Im PDF steht als Quelle blockchainwelt.de. Hast Du evtl. noch die Original URL? Siehe https://bitcoinbeachtravemuende.github.io/DerBitcoinVirus/3-4-vermoegenswerte.html (runterscrollen)

**Comment by KahnsisDeVillain** [comment]
Habe ich rausgesucht und eingetragen.
