### ISSUE TITLE
Typo: Geldmenge

### ISSUE THREAD

**Issue by sectore** [BitcoinBeachTravemuende/DerBitcoinVirus#13]
Was bedeutet `11xxxxxxx1 kommt da noch hinzu` in [https://bitcoinbeachtravemuende.github.io/DerBitcoinVirus/3-3-wozu.html (runterscr](https://bitcoinbeachtravemuende.github.io/DerBitcoinVirus/3-3-wozu.html#die-geldmenge-m3-155-billionen-).

**Comment by KahnsisDeVillain** [comment]
War ein Fehler wurde gelöscht.
