### ISSUE TITLE
Tabelle: Stimmrechte

### ISSUE THREAD

**Issue by sectore** [BitcoinBeachTravemuende/DerBitcoinVirus#14]
Woher stammen die Daten dieser Tabelle? Siehe https://bitcoinbeachtravemuende.github.io/DerBitcoinVirus/3-8-ezb.html (runterscrollen)

![tabelle](https://github.com/BitcoinBeachTravemuende/DerBitcoinVirus/assets/47693/c3508464-c954-41b3-a1a2-b487198eb8db)

- Bitte Quelle angeben.
- Bitte auch nochmal die Summe überprüfen: Scheint `76.9999%` statt `81,3286 %` zu sein.

**Comment by KahnsisDeVillain** [comment]
Bereits aktualisiert, von der EZB selbst natürlich.Kroatien kam  auch neu hinzu.
