### ISSUE TITLE
Quelle: Bild  Cantillon-Effekt

### ISSUE THREAD

**Issue by sectore** [BitcoinBeachTravemuende/DerBitcoinVirus#20]
Quelle zum Bild der spielenden + Copyrights checken Kinder https://bitcoinbeachtravemuende.github.io/DerBitcoinVirus/4-4-cantillon.html

**Comment by KahnsisDeVillain** [comment]
Ja der Link funktioniert nicht..suche noch den Fehler.

**Comment by KahnsisDeVillain** [comment]
Funktioniert jetzt.
