### ISSUE TITLE
Quelle: Bild Phasen

### ISSUE THREAD

**Issue by sectore** [BitcoinBeachTravemuende/DerBitcoinVirus#23]
Woher stammt das Bild für die verschiedenen Phasen: Stealth, Awarness, Mania, Blow https://bitcoinbeachtravemuende.github.io/DerBitcoinVirus/5-1-bitcoin.html

Bitte genaue Quelle angeben.

**Comment by KahnsisDeVillain** [comment]
LinkedIn,bereits eingefügt der Link
