### ISSUE TITLE
Quellen: Bilder im Kapitel 5.3

### ISSUE THREAD

**Issue by sectore** [BitcoinBeachTravemuende/DerBitcoinVirus#24]
Quellenangabe zu beiden Bildern (Alien, CryptoParody) https://bitcoinbeachtravemuende.github.io/DerBitcoinVirus/5-3-fazit.html

**Comment by KahnsisDeVillain** [comment]
Matrix suche ich noch raus,Video wurde unter dem Bitcoin is the Future verlinkt.
