### ISSUE TITLE
Quelle/URL: Tweet @fabthefox

### ISSUE THREAD

**Issue by sectore** [BitcoinBeachTravemuende/DerBitcoinVirus#6]
Link zum Tweet von @fabthefox https://bitcoinbeachtravemuende.github.io/DerBitcoinVirus/einleitung.html

**Comment by KahnsisDeVillain** [comment]
Leider nicht zu finden, bei fast 21K Tweets.

**Comment by fabthefoxx** [comment]
Hier der Tweet: https://x.com/fabthefoxx/status/1565763833813258240

**Comment by KahnsisDeVillain** [comment]
Danke,wurde hinzugefügt.
